Add layout
bk-software/my-dev-knowledge pull request #4
Opened 2022-12-16 14:28 UTC by OriGuyUniqueDev

- added basic layout without styles header, main, and footer
- added login page
- added register page
- added basic routing: /home (layout) / (login page) /register (register page)

2022-12-16 14:50 UTC, bk-software requested changes

2022-12-16 14:50 UTC, bk-software commented on client/src/components/layout/Layout.tsx
> +			<Main></Main>
Layout and Main should have children right?

2022-12-16 14:50 UTC, bk-software commented on client/src/components/signin_register/Signin.tsx
> +const theme = createTheme();
remove the theme from here

2022-12-16 15:18 UTC, OriGuyUniqueDev commented on client/src/components/layout/Layout.tsx
> +			<Main></Main>
i fixed it

2022-12-16 15:19 UTC, OriGuyUniqueDev commented on client/src/components/signin_register/Signin.tsx
> +						backgroundImage: "url(https://source.unsplash.com/random)",
In my vscode, it looks fine.
What can we do?

2022-12-16 15:19 UTC, OriGuyUniqueDev commented on client/src/components/signin_register/Signin.tsx
> +const theme = createTheme();
I removed it

2022-12-16 15:31 UTC, OriGuyUniqueDev commented on client/src/main.tsx
> +const router = createBrowserRouter([
I did it

2022-12-18 16:35 UTC, bk-software commented on client/src/components/signin_register/Signin.tsx
> +						backgroundImage: "url(https://source.unsplash.com/random)",
Did you try to ask google about it?

2022-12-18 16:37 UTC, bk-software commented on client/src/components/signin_register/Signin.tsx
> +function Copyright(props: any) {
It is better that this will move to another component. Right?

2022-12-18 16:37 UTC, merged